# Github Actions workflow to generate documentation
# Uses the following shared task definitions:
# - (checkout, upload artifact) from Github
# - sphinx-action maintained by @ammaraskar
name: Sphinx build

# Controls when the action will run.
# Triggers the workflow on push or pull request events.
on:
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"
        pre-build-command: "mkdir -p /tmp && touch /tmp/sphinx-log && pip3 install sphinx_markdown_builder"
    - uses: actions/upload-artifact@v3
      with:
        name: UserGuideHTML
        path: "doc/_build/html/"
